// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExternalAdapter is an autogenerated mock type for the ExternalAdapter type
type ExternalAdapter struct {
	mock.Mock
}

// Do provides a mock function with given fields: in
func (_m *ExternalAdapter) Do(in string) (string, error) {
	ret := _m.Called(in)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewExternalAdapter interface {
	mock.TestingT
	Cleanup(func())
}

// NewExternalAdapter creates a new instance of ExternalAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExternalAdapter(t mockConstructorTestingTNewExternalAdapter) *ExternalAdapter {
	mock := &ExternalAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
