// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// InternalAdapter is an autogenerated mock type for the InternalAdapter type
type InternalAdapter struct {
	mock.Mock
}

// Do provides a mock function with given fields:
func (_m *InternalAdapter) Do() (bool, error) {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewInternalAdapter interface {
	mock.TestingT
	Cleanup(func())
}

// NewInternalAdapter creates a new instance of InternalAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInternalAdapter(t mockConstructorTestingTNewInternalAdapter) *InternalAdapter {
	mock := &InternalAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
